// Generates icons.client.tsx: Lucide icons (ISC license) rasterized to
// white-on-transparent PNG data URIs. The plugin client runtime can only
// require react/react-native/@tanstack/react-query/zod + the SDK, and
// react-native-svg pulls in forbidden react-native internals — so icons are
// plain RN <Image> with tintColor. Run: node scripts/gen-icons.mjs
import sharp from "sharp";
import { writeFileSync } from "node:fs";

const SIZE = 96; // 4x supersample of the 24-unit grid for crisp tinting

// Lucide path data, 24x24 grid, stroke-based, strokeWidth 2, round caps.
const ICONS = {
  overview: `<rect width="7" height="7" x="3" y="3" rx="1"/><rect width="7" height="7" x="14" y="3" rx="1"/><rect width="7" height="7" x="14" y="14" rx="1"/><rect width="7" height="7" x="3" y="14" rx="1"/>`,
  issues: `<circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="1" fill="white"/>`,
  board: `<rect width="18" height="18" x="3" y="3" rx="2"/><path d="M9 3v18"/><path d="M15 3v18"/>`,
  pulls: `<circle cx="18" cy="18" r="3"/><circle cx="6" cy="6" r="3"/><path d="M13 6h3a2 2 0 0 1 2 2v7"/><line x1="6" x2="6" y1="9" y2="21"/>`,
  actions: `<polygon points="6 3 20 12 6 21 6 3"/>`,
  comment: `<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>`,
};

const entries = [];
for (const [name, body] of Object.entries(ICONS)) {
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="${SIZE}" height="${SIZE}" viewBox="0 0 24 24" ` +
    `fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${body}</svg>`;
  const png = await sharp(Buffer.from(svg)).png().toBuffer();
  entries.push(`  ${name}: "data:image/png;base64,${png.toString("base64")}",`);
}

const output = `// GENERATED by scripts/gen-icons.mjs — edit that file, not this one.
// Icons are white-on-transparent PNGs tinted via the tintColor style.
import React from "react";
import { Image } from "react-native";

const ICONS = {
${entries.join("\n")}
} as const;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  size = 14,
  color,
}: {
  name: IconName;
  size?: number;
  color: string;
}) {
  return (
    <Image
      source={{ uri: ICONS[name] }}
      style={{ width: size, height: size, tintColor: color }}
      accessibilityElementsHidden
      importantForAccessibility="no"
    />
  );
}
`;

writeFileSync(new URL("../icons.client.tsx", import.meta.url), output);
console.log(`wrote icons.client.tsx (${Object.keys(ICONS).length} icons)`);
